openapi: 3.0.1
info:
  title: Hnefatafl API
  version: 1.0.0
paths:
  /games:
    post:
      summary: Start a new game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameCreateRequest'
      responses:
        '200':
          description: Game started
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    GameCreateRequest:
      type: object
      properties:
        type:
          type: string
